-- Glow Salon CRM migration.
-- Run once in the Supabase SQL Editor: on the test project first, then on live.
-- Adds to the existing schema; nothing the n8n workflows use is renamed.
-- Spec: docs/superpowers/specs/2026-09-24-glow-salon-crm-design.md

begin;

-- =============================================================================
-- Section 1: tables, columns, logins and roles, closed days
-- =============================================================================

-- Settings: slot length and weekly closed days (0 = Sunday ... 6 = Saturday)
alter table salon_settings
  add column slot_minutes int not null default 30
    check (slot_minutes in (15, 30, 45, 60)),
  add column closed_weekdays smallint[] not null default '{}'
    check (closed_weekdays <@ array[0, 1, 2, 3, 4, 5, 6]::smallint[]);

-- One-off closures such as holidays
create table closed_dates (
  closed_on date primary key,
  reason text,
  created_at timestamptz not null default now()
);
alter table closed_dates enable row level security;

-- Services: automatic ids, plus the card text, icon and order the website shows
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'services'
      and column_name = 'id' and is_identity = 'YES'
  ) then
    alter table services alter column id add generated by default as identity;
  end if;
end;
$$;
select setval(pg_get_serial_sequence('public.services', 'id'),
              coalesce((select max(id) from services), 0) + 1, false);

alter table services
  add column description text,
  add column icon text not null default 'i-scissors'
    check (icon in ('i-scissors', 'i-palette', 'i-lines', 'i-brush', 'i-drop', 'i-leaf')),
  add column sort_order int not null default 0;

update services s
set description = v.description, icon = v.icon
from (values
  (1, 'Cut, wash, and blow-dry',   'i-scissors'),
  (2, 'Clean cut and style',       'i-scissors'),
  (3, 'Full color or refresh',     'i-palette'),
  (4, 'Smooth, straight hair',     'i-lines'),
  (5, 'Shape, clean, and polish',  'i-brush'),
  (6, 'Soak, scrub, and polish',   'i-brush'),
  (7, 'Relaxing soak and massage', 'i-drop'),
  (8, 'Ease tension and unwind',   'i-leaf')
) as v(id, description, icon)
where s.id = v.id;
update services set sort_order = id;

-- Bookings keep the duration and price they were booked with
alter table bookings
  add column duration_minutes int,
  add column price numeric;

update bookings b
set duration_minutes = s.duration_minutes, price = s.price
from services s
where s.id = b.service_id;

alter table bookings
  alter column duration_minutes set not null,
  alter column price set not null,
  add constraint bookings_duration_minutes_check check (duration_minutes > 0),
  add constraint bookings_price_check check (price >= 0),
  drop constraint bookings_source_check,
  add constraint bookings_source_check
    check (source = any (array['website', 'ai_chat', 'walk_in', 'phone']));

-- Any insert that leaves them out (including from n8n) gets them from the service
create function fill_booking_snapshot() returns trigger
language plpgsql set search_path = public as $$
begin
  if new.duration_minutes is null or new.price is null then
    select coalesce(new.duration_minutes, s.duration_minutes), coalesce(new.price, s.price)
      into new.duration_minutes, new.price
    from services s where s.id = new.service_id;
  end if;
  return new;
end;
$$;

create trigger bookings_fill_snapshot
  before insert on bookings
  for each row execute function fill_booking_snapshot();

-- CRM logins: every Supabase login gets a profile; role none has no access
create table staff_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'none' check (role in ('none', 'staff', 'owner')),
  created_at timestamptz not null default now()
);
alter table staff_profiles enable row level security;

create function handle_new_auth_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into staff_profiles (user_id, email)
  values (new.id, new.email)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_auth_user();

insert into staff_profiles (user_id, email)
select id, email from auth.users
on conflict (user_id) do nothing;

-- Role of the logged-in user ('none' when not logged in or not approved)
create function app_role() returns text
language sql stable security definer set search_path = public as $$
  select coalesce((select role from staff_profiles where user_id = auth.uid()), 'none')
$$;

create function is_staff() returns boolean
language sql stable security definer set search_path = public as $$
  select app_role() in ('staff', 'owner')
$$;

create function is_owner() returns boolean
language sql stable security definer set search_path = public as $$
  select app_role() = 'owner'
$$;

-- The one place the closed-day rule lives. Null means open.
create function closed_reason(p_date date) returns text
language sql stable set search_path = public as $$
  select coalesce(
    (select case
              when coalesce(btrim(reason), '') = '' then 'We''re closed that day.'
              else format('We''re closed that day (%s).', btrim(reason))
            end
       from closed_dates where closed_on = p_date),
    (select format('We''re closed on %ss.', to_char(p_date, 'FMDay'))
       from salon_settings
      where id = 1 and extract(dow from p_date)::smallint = any (closed_weekdays))
  )
$$;

commit;
